services:
  - type: web
    name: vibecode-app
    env: node
    region: oregon
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false  
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
    autoDeploy: true
    
databases:
  - name: vibecode-db
    plan: starter
    region: oregon
