# render.yaml: Configuration for deploying VibeCode on Render
# This file defines three services:
# 1. A PostgreSQL database for data persistence.
# 2. A Node.js Express backend service.
# 3. A React/Next.js frontend web service.

services:
  - type: static
    name: vibecode-static
    env: static
    rootDir: ./client
    build:
      command: "echo 'No build needed for static site'"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
